UrlData<-"https://d396qusza40orc.cloudfront.net/exdata%2Fdata%2Fhousehold_power_consumption.zip"
download.file(UrlData,destfile = "./data.zip")
unzip("./data.zip",exdir = ".")

library(lubridate)
library(grDevices)
test<-read.table("household_power_consumption.txt",sep = ";",header = TRUE)
test2<-subset.data.frame(test,test$Date=="1/2/2007"|test$Date=="2/2/2007")
test2$Global_active_power<-as.numeric(as.character(test2$Global_active_power))
test2$Global_reactive_power<-as.numeric(as.character(test2$Global_reactive_power))
test2$Voltage<-as.numeric(as.character(test2$Voltage))
test2$Sub_metering_1<-as.numeric(as.character(test2$Sub_metering_1))
test2$Sub_metering_2<-as.numeric(as.character(test2$Sub_metering_2))
test2$Sub_metering_3<-as.numeric(as.character(test2$Sub_metering_3))
test2$DateTime<-paste(test2$Date," ",test2$Time)
test2$DateTime<-dmy_hms(test2$DateTime)
png(filename = "plot4.png")
par(mfcol= c(2,2))
with(test2,{
  plot(DateTime,Global_active_power,xlab = "",ylab = "Global Active Power",col="white",pch=20)
  lines(DateTime,Global_active_power,xlab = "",ylab = "Global Active Power",pch=20)
  plot(DateTime,Sub_metering_1,xlab = "",ylab = "Energy sub metering",col="white")
  lines(DateTime,Sub_metering_1,xlab = "",ylab = "Energy sub metering")
  lines(DateTime,Sub_metering_2,xlab = "",ylab = "Energy sub metering",col="red")
  lines(DateTime,Sub_metering_3,xlab = "",ylab = "Energy sub metering",col="blue")
  legend("topright", lty = 1 ,col = c("black","red","blue"), legend = c("Sub_metering_1","Sub_metering_2","Sub_metering_3"))
  plot(DateTime,Voltage,xlab = "datetime",ylab = "Voltage",col="white",pch=20)
  lines(DateTime,Voltage,xlab = "datetime",ylab = "Voltage",pch=20)
  plot(DateTime,Global_reactive_power,xlab = "datetime",ylab = "Global_reactive_power",col="white",pch=20)
  lines(DateTime,Global_reactive_power,xlab = "datetime",ylab = "Global_reactive_power",pch=20)
})
dev.off(dev.cur())