UrlData<-"https://d396qusza40orc.cloudfront.net/exdata%2Fdata%2Fhousehold_power_consumption.zip"
download.file(UrlData,destfile = "./data.zip")
unzip("./data.zip",exdir = ".")

library(lubridate)
library(grDevices)
test<-read.table("household_power_consumption.txt",sep = ";",header = TRUE)
test2<-subset.data.frame(test,test$Date=="1/2/2007"|test$Date=="2/2/2007")
test2$Sub_metering_1<-as.numeric(as.character(test2$Sub_metering_1))
test2$Sub_metering_2<-as.numeric(as.character(test2$Sub_metering_2))
test2$Sub_metering_3<-as.numeric(as.character(test2$Sub_metering_3))
test2$DateTime<-paste(test2$Date," ",test2$Time)
test2$DateTime<-dmy_hms(test2$DateTime)
png(filename = "plot3.png")
plot(test2$DateTime,test2$Sub_metering_3,xlab = "",ylab = "Energy sub metering",col="white") 
plot(test2$DateTime,test2$Sub_metering_2,xlab = "",ylab = "Energy sub metering",col="white")
plot(test2$DateTime,test2$Sub_metering_1,xlab = "",ylab = "Energy sub metering",col="white")
lines(test2$DateTime,test2$Sub_metering_1,xlab = "",ylab = "Energy sub metering")
lines(test2$DateTime,test2$Sub_metering_2,xlab = "",ylab = "Energy sub metering",col="red")
lines(test2$DateTime,test2$Sub_metering_3,xlab = "",ylab = "Energy sub metering",col="blue")
legend("topright", lty = 1 ,col = c("black","red","blue"), legend = c("Sub_metering_1","Sub_metering_2","Sub_metering_3"))
dev.off(dev.cur())